CisReview/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'courses#index'
	
  resources :courses do
  	resources :reviews, except: [:show, :index]
  end

  resources :instructors

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

CisReview/app/models/instructor.rb
class Instructor < ApplicationRecord
  has_attached_file :image, styles: { medium: "200x200#"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_many :courses, dependent: :delete_all
  has_many :reviews
	validates :first_name, presence: true
	validates :last_name, presence: true

	validate :f_capitalize
  validate :l_capitalize

    def f_capitalize
      errors.add(:first_name, 'must be capitalized') if first_name && first_name[0] != first_name[0].upcase
    end

    def l_capitalize
      errors.add(:last_name, 'must be capitalized') if last_name && last_name[0] != last_name[0].upcase
    end
end

CisReview/app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
    @reviews = Review.where(instructor_id: @instructor.id).order("created_at DESC")
    if (@reviews.blank?)
      @avg_difficulty = 0
      @avg_workload = 0
      @avg_quality = 0
    else
      @avg_difficulty = @reviews.average(:difficulty).round(2)
      @avg_workload = @reviews.average(:workload).round(2)
      @avg_quality = @reviews.average(:quality).round(2)
    end
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:first_name, :last_name, :image)
    end
end

CisReview/app/helpers/instructors_helper.rb
module InstructorsHelper
end

CisReview/app/views/instructors/_form.html.erb
<div class="jumbotron">

<%= form_with(model: instructor,  local: true, html: { multipart: true }) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :instructor_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :instructor_last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

CisReview/app/views/instructors/edit.html.erb
<div class="container">
<div class = "table">

<h2>Editing Instructor</h2>

<%= render 'form', instructor: @instructor %>

<div class = "btn btn-default">
<%= link_to 'Show', @instructor %> 
</div>
<div class = "btn btn-default">
<%= link_to 'Back', instructors_path %>
</div>

</div>
<%=yield%>
</div>

CisReview/app/views/instructors/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<div class="jumbotron">

<h2>Instructors</h2>

<table class = "table">
  <thead>
    <tr>
      <th colspan = "1">Image</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%=image_tag instructor.image.url(:medium) %></td>
        <td><%= instructor.first_name %></td>
        <td><%= instructor.last_name %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class = "btn btn-default">
<%= link_to 'New Instructor', new_instructor_path %>
</div>

</div>

<%=yield%>
</div>

CisReview/app/views/instructors/new.html.erb
<div class="container">

<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<div class = "btn btn-default">
<%= link_to 'Back', instructors_path %>
</div>

<%=yield%>
</div>

CisReview/app/views/instructors/show.html.erb
<div class = "container">
<div class="jumbotron">

<%= image_tag @instructor.image.url(:medium) %>

<div class = "panel-body">
<h4>
  <strong>First name:</strong>
  <%= @instructor.first_name %>
</h4>

<h4>
  <strong>Last name:</strong>
  <%= @instructor.last_name %>
</h4>

<h4>
	<strong>Difficulty:</strong>
	<%=@avg_difficulty %>
</h4>

<h4>
	<strong>Quality:</strong>
	<%=@avg_quality %>
</h4>

<h4>
	<strong>WorkLoad:</strong>
	<%=@avg_workload%>
</h4>

</div>
<div class = "panel panel-primary">

<div class = "panel-heading">
<h3> Reviews: </h3>
</div>

<div class = "panel-body">

<p>
	<% if @reviews.blank? %>
  <h3> ... Unfortunately, this professor is probably new to Penn... </h3>
  <% else %>
    <% @reviews.each do |review| %>
     
       <h4> Difficulty: <%=review.difficulty%>   
            Workload: <%=review.workload%>  
            Quality: <%=review.quality%>  
            Course: <% @course =  Course.find(review.course_id) %>
                   <%= @course.number %>
      </h4>
      <h4>
        <%=review.comment %>
      </h4>
    <%end%>
  <%end%>
 </p>

</div>
</div>

<div class = "btn btn-default">
<%= link_to 'Edit', edit_instructor_path(@instructor) %>
</div>
<div class = "btn btn-default">
<%= link_to 'Back', instructors_path %>
</div>

</div>
</div>